name: Validate PR
on: [ push ]
jobs:
    check_formatting:
        runs-on: ubuntu-latest
        name: Check Formatting
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v2
              with:
                dotnet-version: '6.0.x'
            - run: |
                dotnet tool restore
                dotnet tool install csharpier
                dotnet csharpier --check

